# -*- coding: utf-8 -*-
"""
Created on Mon May  8 14:31:28 2017
Estrategia.py
@author: Diego Ochoa
"""

from abc import ABCMeta, abstractmethod
import datetime
import random
import time
try:
    import Queue as queue
except ImportError:
    import queue

import numpy as np
import pandas as pd

from Eventos import EventoSenal
import statsmodels.api as sm
import statsmodels.tsa.stattools as ts

#from Datos import BinanceData


class Estrategia(object):
    """
    Strategy is an abstract base class providing an interface for
    all subsequent (inherited) strategy handling objects.

    The goal of a (derived) Strategy object is to generate Signal
    objects for particular symbols based on the inputs of Bars 
    (OHLCV) generated by a DataHandler object.

    This is designed to work both with historic and live data as
    the Strategy object is agnostic to where the data came from,
    since it obtains the bar tuples from a queue object.
    """

    __metaclass__ = ABCMeta

    @abstractmethod
    def calcular_senales(self):
        """
        Provee el mecanismo para calcular las señales de una estrategia.
        """
        raise NotImplementedError("Implementar calcular_senales()")

class PairsTradingHFT(Estrategia):
        def __init__(self, velas, eventos,ventanaOLS=180,Low = 1,High=3.0, signal_logger=None):

            """
            Implementa el método de reversión a la media de Avellaneda (2007)
            inicializa la estrategia.
            Parámetros
            velas - El objeto de AdminDatos que gotea la info en la estrategia
            eventos- La fila de eventos ( como objeto).
            ventanaOLS- Parámetro para el cálculo del OLS que genera el Hedge Ratio
            prom_Movil- Promedio usado para los Stops.
            signal_logger - SignalOrderLogger instance for debugging (optional)
            """
            self.velas = velas
            self.lista_nemos = self.velas.lista_nemos
            self.eventos = eventos
            self.ventanaOLS = ventanaOLS
            self.zHigh=High
            self.zLow=Low
            self.par=self.velas.lista_nemos
            self.datetime=datetime.datetime.utcnow()
            self.hedge_ratio = 1
            self.signal_logger = signal_logger
        # Cambiar a True si el activo está en el mercado
            self.largoMdo =False
            self.cortoMdo=False
            # Track pending orders to prevent duplicate signals
            self.ordenes_pendientes = {nemo: None for nemo in self.lista_nemos}
            
            # ✅ SMART DEDUPLICATION: Track last processed candle timestamp per symbol
            # Prevents processing the same candle multiple times (from WebSocket + Heartbeat)
            self.last_processed_candle = {nemo: None for nemo in self.lista_nemos}
            self._candle_dedup_count = 0  # Statistics tracking
            
            # ✅ PAIR-COMPLETE GATE: Track which symbols have been updated this heartbeat
            # Only evaluate signals when ALL symbols in the pair have fresh data
            self._updated_symbols_this_cycle = set()
            self._last_cycle_candle_time = {nemo: None for nemo in self.lista_nemos}
            
            # Reference to portfolio for position sync (set by trading.py)
            self.portafolio = None

            # ─── SLOW LAYER (daily OLS) ────────────────────────
            # Structural parameters computed on 1d candles via REST.
            # Aligned with CointegrationMonitor (CoinAPI daily, ~90 days).
            # Updated every SLOW_LAYER_INTERVAL seconds.
            self.SLOW_LAYER_INTERVAL = 21600  # refresh every 6 hours
            self.SLOW_LAYER_WINDOW = 180      # 180 daily candles — aligned with MRBacktest OLS_WINDOW
            # Random offset (0-600s / 10 min) so pairs don't all
            # refresh at once and burst the API rate limit.
            self._slow_layer_offset = random.uniform(0, 600)
            self._slow_layer_first_done = False
            self.slow_params = {
                'hedge_ratio': None,
                'spread_mean': None,
                'spread_std': None,
                'is_cointegrated': False,
                'last_update': 0,
                'adf_stat': None,
                'adf_pvalue': None,
                'eg_pvalue': None,
            }
            self._slow_layer_ready = False

        def set_portafolio(self, portafolio):
            """
            Set reference to portfolio for position synchronization.
            Called by trading.py after portfolio is created.
            """
            self.portafolio = portafolio
            print(f"✅ Strategy linked to portfolio for position sync")

        # ─── SLOW LAYER (daily OLS via REST) ──────────────
        def _slow_layer_update(self):
            """
            Recompute structural OLS parameters using 1-day candles
            fetched via the Binance REST API.

            Option A (2026-04-27): CointegrationMonitor is the SOLE
            authority on pair selection. The live slow layer no longer
            gates entries on its own EG/ADF result — doing so with a
            90-day rolling window refreshed every 6 hours produced too
            many false positives that blocked profitable entries (the
            monitor selects on 180 days; the live gate fired when a
            single new daily bar temporarily failed the 90-day test).

            This method now:
              • Computes hedge_ratio, spread_mean, spread_std (OLS) —
                required for z-score normalisation.
              • Runs EG+ADF for DIAGNOSTIC/MONITORING purposes only.
                Results are stored in slow_params and visible in the
                dashboard but do NOT block entry signals.
              • Sets is_cointegrated=True whenever the OLS succeeds
                (valid spread and spread_std > 0). Backward-compatible
                with LiveMonitor and live_state_*.json readers.

            To re-enable the cointegration gate, add:
                if not coint: return   (after coint = ... line)
            and restore the block in calcular_senal_pares().
            """
            try:
                sym_y = self.par[0]
                sym_x = self.par[1]

                # Fetch daily OHLCV via REST
                # +1 so we can exclude the current (possibly incomplete)
                # bar from OLS, matching MRBacktest's causal framework.
                df_y = self.velas.get_perpetual_ohlcv(
                    sym_y,
                    interval='1d',
                    limit=self.SLOW_LAYER_WINDOW + 1,
                )
                df_x = self.velas.get_perpetual_ohlcv(
                    sym_x,
                    interval='1d',
                    limit=self.SLOW_LAYER_WINDOW + 1,
                )

                if df_y is None or df_x is None:
                    print("⚠️  Slow-layer: REST fetch returned None")
                    return
                if len(df_y) < 30 or len(df_x) < 30:
                    print(
                        f"⚠️  Slow-layer: not enough data "
                        f"(y={len(df_y)}, x={len(df_x)})"
                    )
                    return

                # Align lengths
                n = min(len(df_y), len(df_x))
                all_y = np.array(df_y['close'].astype(float).values[-n:])
                all_x = np.array(df_x['close'].astype(float).values[-n:])

                # Causal split: OLS on [:-1], bar [-1] reserved for
                # fast-layer z-score (out-of-sample, matching MRBacktest).
                if len(all_y) >= self.SLOW_LAYER_WINDOW + 1:
                    y = all_y[:-1]
                    x = all_x[:-1]
                else:
                    y = all_y
                    x = all_x

                if np.std(y) < 1e-8 or np.std(x) < 1e-8:
                    print("⚠️  Slow-layer: zero variance")
                    return

                # OLS hedge ratio on log prices (causal: excludes current bar)
                log_y = np.log(y)
                log_x = np.log(x)
                model  = sm.OLS(log_y, sm.add_constant(log_x))
                result = model.fit()
                hr     = result.params[-1]   # slope = hedge ratio

                # Spread & stats from OLS window only (causal: excludes current bar)
                spread  = log_y - hr * log_x
                sp_mean = np.mean(spread)
                sp_std  = np.std(spread)
                if sp_std < 1e-8:
                    print("⚠️  Slow-layer: spread std ≈ 0")
                    return

                # ── Diagnostic EG+ADF (NOT used as trading gate) ────────────
                # Retained for monitoring and dashboard visibility.
                # These tests are INFORMATIONAL ONLY — they do not block
                # entries. CointegrationMonitor is the gate authority.
                try:
                    _, eg_pval, _ = ts.coint(log_y, log_x)
                    adf = ts.adfuller(spread, maxlag=12)
                    adf_stat = adf[0]
                    adf_pval = adf[1]
                    crit_5   = adf[4]['5%']
                    adf_coint = (adf_stat <= crit_5) or (adf_pval <= 0.05)
                    coint_diag = (eg_pval <= 0.05) and adf_coint
                except Exception:
                    eg_pval = adf_stat = adf_pval = None
                    coint_diag = None

                # is_cointegrated = True whenever OLS succeeds (spread is valid).
                # The field is kept for backward compatibility with LiveMonitor
                # and live_state_*.json — it no longer gates trading logic.
                self.slow_params.update({
                    'hedge_ratio':    hr,
                    'spread_mean':    sp_mean,
                    'spread_std':     sp_std,
                    'is_cointegrated': True,        # OLS valid → ready to trade
                    'adf_stat':       adf_stat,
                    'adf_pvalue':     adf_pval,
                    'eg_pvalue':      eg_pval,
                    'last_update':    time.time(),
                })
                self._slow_layer_ready = True

                diag_tag = (
                    "✅" if coint_diag else
                    "⚠️ [diag only, not gating]" if coint_diag is not None else
                    "—"
                )
                print(
                    f"🔬 Slow-layer updated | HR={hr:.4f} "
                    f"| spread μ={sp_mean:.6f} σ={sp_std:.6f} "
                    f"| EG p={eg_pval:.4f} ADF={adf_stat:.3f} p={adf_pval:.4f} "
                    f"| coint_diag={diag_tag} [gate: CointegrationMonitor]"
                )

            except Exception as e:
                print(f"⚠️  Slow-layer error: {e}")
                import traceback
                traceback.print_exc()

        def sync_position_flags(self):
            """
            Synchronize largoMdo/cortoMdo flags with actual portfolio positions.
            
            This ensures strategy state matches reality, especially after:
            - Manual closes on exchange
            - Partial fills
            - System restarts
            - State drift over time
            
            SPREAD POSITION LOGIC:
            - LARGO spread = Long Y (par[0]) + Short X (par[1]) → pos_y > 0, pos_x < 0
            - CORTO spread = Short Y (par[0]) + Long X (par[1]) → pos_y < 0, pos_x > 0
            """
            if self.portafolio is None:
                return  # Portfolio not yet linked
            
            pos_y = self.portafolio.posiciones_actuales.get(self.par[0], 0)
            pos_x = self.portafolio.posiciones_actuales.get(self.par[1], 0)
            
            old_largo = self.largoMdo
            old_corto = self.cortoMdo
            
            # Determine spread position from actual holdings
            # LARGO spread: long Y (pos_y > 0), short X (pos_x < 0)
            # CORTO spread: short Y (pos_y < 0), long X (pos_x > 0)
            
            if pos_y > 0 and pos_x < 0:
                self.largoMdo = True
                self.cortoMdo = False
            elif pos_y < 0 and pos_x > 0:
                self.largoMdo = False
                self.cortoMdo = True
            elif pos_y == 0 and pos_x == 0:
                # Both flat = no spread position
                self.largoMdo = False
                self.cortoMdo = False
            else:
                # Mixed state (both positive, both negative, one zero) = uncertain
                # Keep current flags but log warning
                if pos_y != 0 or pos_x != 0:
                    print(f"⚠️  Position state unclear: {self.par[0]}={pos_y}, {self.par[1]}={pos_x}")
            
            # Log if state changed
            if old_largo != self.largoMdo or old_corto != self.cortoMdo:
                print(f"🔄 Position flags synced: largoMdo={old_largo}→{self.largoMdo}, cortoMdo={old_corto}→{self.cortoMdo}")
                print(f"   Actual positions: {self.par[0]}={pos_y}, {self.par[1]}={pos_x}")

        def actualiza_orden_pendiente(self, nemo, direccion):
            """Called when portfolio generates an order"""
            self.ordenes_pendientes[nemo] = direccion
            
        def limpia_orden_pendiente(self, nemo):
            """Called when order fills"""
            self.ordenes_pendientes[nemo] = None
        
        def get_deduplication_stats(self):
            """
            Returns statistics about candle deduplication.
            Useful for debugging and monitoring.
            """
            return {
                'duplicates_skipped': self._candle_dedup_count,
                'last_processed_candles': self.last_processed_candle.copy()
            }

        def calcular_senalXY(self, z_last):
            """
            Calcula la señal para el par de activos que será enviada al generador de
            señales
            """
            # ✅ SYNC position flags with actual portfolio positions
            # This ensures strategy state matches reality after manual closes, partial fills, etc.
            self.sync_position_flags()
            
            senal_x=None
            senal_y=None
            p0=self.par[0]
            p1=self.par[1]
            dt=self.datetime
            hr=abs(self.hedge_ratio)
            
            # Debug: Show current state
            print(f"📊 Z={z_last:.2f} | zHigh={self.zHigh} | largoMdo={self.largoMdo} | cortoMdo={self.cortoMdo} | pendientes={self.ordenes_pendientes}")

            #(2)Si estamos largo Spread y entre zLow y -zLow → EXIT FIRST (priority over entry)

            if abs(z_last)<=self.zLow and self.largoMdo==True:
                print(f'Saliendo Largo {p0} - Saliendo Corto {p1}')
                self.largoMdo=False
                senal_y=EventoSenal(1,p0,dt,'FUERA',1.0)
                senal_x=EventoSenal(1,p1,dt,'FUERA',1.0)
                print(f'Fuera Largo {p0} - Fuera Corto {p1}')

            #(4)Si estamos Cortos Sprd pero entre zLow y -zLow → EXIT FIRST (priority over entry)

            elif abs(z_last)<=self.zLow and self.cortoMdo==True:
                print
                self.cortoMdo=False
                senal_y=EventoSenal(1,p0,dt,'FUERA',1.0)
                senal_x=EventoSenal(1,p1,dt,'FUERA',1.0)
                print(f'Fuera Corto {p0} - Fuera Largo {p1}' )

            #(1)Si estamos neutros Spread pero abajo de -zHigh → ENTER LONG

            elif z_last<=-self.zHigh and not self.largoMdo and not self.cortoMdo and self.ordenes_pendientes.get(p0) is None and self.ordenes_pendientes.get(p1) is None:
                print(f'Entrando Largo {p0} - Corto {p1} * {hr}')
                self.largoMdo=True
                senal_y=EventoSenal(1, p0, dt, 'LARGO', 1.0)
                senal_x=EventoSenal(1,p1,dt,'CORTO',hr)
                print(f'Largo {p0} - Corto {p1} * {hr}')
                
                # Log signals
                if self.signal_logger:
                    self.signal_logger.log_signal(senal_y, z_score=z_last, hedge_ratio=1.0)
                    self.signal_logger.log_signal(senal_x, z_score=z_last, hedge_ratio=hr)

            #(3) Si estamos Neutros y arriba de zHigh → ENTER SHORT

            elif z_last>=self.zHigh and not self.cortoMdo and not self.largoMdo and self.ordenes_pendientes.get(p0) is None and self.ordenes_pendientes.get(p1) is None:
                print(f'Entrando Corto {p0} - Largo {p1} * {hr}')
                self.cortoMdo=True
                senal_y=EventoSenal(1,p0,dt,'CORTO',1.0)
                senal_x=EventoSenal(1,p1,dt,'LARGO',hr)
                print(f'Corto {p0} - Largo {p1} * {hr}')
       

            return senal_y , senal_x

        #test de Cointegración Dickey Fuller Aumentado
        def test_cointegracion(self,x, y):
            result = sm.OLS(x, y).fit()
            return ts.adfuller(result.resid) 

        def calcular_senal_pares(self): 
            """
            Dual-timeframe signal engine:

            SLOW LAYER  – Daily candles via REST, refreshed every
            SLOW_LAYER_INTERVAL seconds.  Provides stable OLS
            hedge_ratio, spread mean/std for z-score normalisation.

            FAST LAYER  – Latest 1-min close prices from the
            WebSocket buffer.  Computes real-time spread and
            z-score using the slow-layer structural parameters.

            Pair selection authority: CointegrationMonitor (daily
            ranking).  The live slow layer no longer gates entries
            on its own EG/ADF result (Option A, 2026-04-27) — a
            90-day rolling test refreshed every 6 hours produced
            too many false positives.  Protection is provided by
            the z-score stop-loss in calcular_senalXY instead.
            """
            # ── 1. Refresh slow layer if stale ──────────────
            now = time.time()
            stale = (
                now - self.slow_params['last_update']
                > self.SLOW_LAYER_INTERVAL
            )
            if not self._slow_layer_first_done:
                # First refresh: apply random offset to stagger across pairs
                if now - self.slow_params['last_update'] < self._slow_layer_offset:
                    pass   # wait for offset before first refresh
                else:
                    self._slow_layer_update()
                    self._slow_layer_first_done = True
            elif stale or not self._slow_layer_ready:
                self._slow_layer_update()

            # Guard: OLS parameters must exist before computing z-score
            if not self._slow_layer_ready:
                print("⏳ Slow layer not ready – skipping signal")
                return

            hr = self.slow_params['hedge_ratio']
            sp_mean = self.slow_params['spread_mean']
            sp_std = self.slow_params['spread_std']

            # ── 2. Fast layer: real-time z-score ────────────
            # Use a short 1-min window (e.g. 60 bars = 1 hour)
            # just to get the latest close prices
            fast_window = min(self.ventanaOLS, 60)
            df_y = self.velas.get_valor_ultimas_velas(
                self.par[0], 'close', N=fast_window,
            )
            df_x = self.velas.get_valor_ultimas_velas(
                self.par[1], 'close', N=fast_window,
            )

            if df_y is None or df_x is None:
                return
            if len(df_y) == 0 or len(df_x) == 0:
                return

            # Current spread using slow-layer HR on LOG prices
            last_y = float(df_y[-1])
            last_x = float(df_x[-1])

            if last_y <= 0 or last_x <= 0:
                return

            spread_now = np.log(last_y) - hr * np.log(last_x)

            # Z-score normalised by slow-layer mean/std
            z_last = (spread_now - sp_mean) / sp_std

            # Also keep self.hedge_ratio so calcular_senalXY
            # uses the correct notional ratio
            self.hedge_ratio = hr

            print(
                f"📈 Fast z={z_last:.3f} | "
                f"spread={spread_now:.6f} | "
                f"μ={sp_mean:.6f} σ={sp_std:.6f} | "
                f"HR={hr:.4f}"
            )

            # ── 3. Generate signals via existing logic ──────
            senal_y, senal_x = self.calcular_senalXY(z_last)
            if senal_y is not None and senal_x is not None:
                self.eventos.put(senal_y)
                self.eventos.put(senal_x)
    
        def calcular_senales(self, evento):
            """
            Calcula las señales según los últimos datos de mercado.
            
            Implements SMART DEDUPLICATION to prevent processing the same candle
            multiple times (from WebSocket + Heartbeat sources).
            
            ✅ PAIR-COMPLETE GATE: Only evaluates signals when ALL symbols in the
            pair have received fresh data for this cycle. This prevents:
            - Double Z-score calculation with stale data on one leg
            - Immediate re-entry after exit due to Z-score flip between legs
            """

            if evento.type == 'MERCADO':
                # ✅ SMART DEDUPLICATION: Check if this candle was already processed
                nemo = evento.nemo
                # Get candle timestamp (prefer close_time, fallback to timestamp)
                candle_time = None
                if hasattr(evento, 'close_time') and evento.close_time is not None:
                    candle_time = evento.close_time
                elif hasattr(evento, 'timestamp') and evento.timestamp is not None:
                    candle_time = evento.timestamp
                elif hasattr(evento, 'open_time') and evento.open_time is not None:
                    candle_time = evento.open_time
                elif hasattr(evento, 'start_time') and evento.start_time is not None:
                    candle_time = evento.start_time
                elif hasattr(evento, 'end_time') and evento.end_time is not None:
                    candle_time = evento.end_time
                
                # Type validation - ensure candle_time is not a type/class
                if candle_time is not None and isinstance(candle_time, type):
                    print(f"⚠️ Invalid timestamp type detected for {nemo}: {candle_time}")
                    print(f"   Skipping this event (pair-complete gate requires valid timestamps)")
                    return
                
                if candle_time is None:
                    # No timestamp available, skip (pair-complete gate requires timestamps)
                    print(f"⚠️ No timestamp found for {nemo} evento, skipping")
                    return
                
                # Check if we've already processed this candle
                last_processed = self.last_processed_candle.get(nemo)
                
                if last_processed is not None and candle_time <= last_processed:
                    # This candle was already processed, skip to prevent duplicate signals
                    self._candle_dedup_count += 1
                    if self._candle_dedup_count % 10 == 0:  # Log every 10th duplicate
                        print(f"🔄 Skipped duplicate candle for {nemo} (#{self._candle_dedup_count} total)")
                        print(f"   Current: {candle_time}, Last processed: {last_processed}")
                    return
                
                # Update last processed timestamp
                self.last_processed_candle[nemo] = candle_time
                
                # Update self.datetime to the candle timestamp for signal creation
                self.datetime = candle_time
                
                # ✅ PAIR-COMPLETE GATE: Register this symbol as updated
                self._updated_symbols_this_cycle.add(nemo)
                self._last_cycle_candle_time[nemo] = candle_time
                
                # Check if ALL symbols in the pair have fresh data
                all_symbols_updated = all(
                    s in self._updated_symbols_this_cycle for s in self.lista_nemos
                )
                
                if not all_symbols_updated:
                    # Not all symbols have updated yet — wait for the rest
                    pending = [s for s in self.lista_nemos if s not in self._updated_symbols_this_cycle]
                    print(f"⏳ Pair-gate: {nemo} updated, waiting for {pending}")
                    return
                
                # ✅ ALL symbols have fresh data — evaluate signals ONCE
                print(f"✅ Pair-gate: All symbols updated {dict(self._last_cycle_candle_time)} → evaluating signals")
                
                # Reset the cycle tracker for the next heartbeat
                self._updated_symbols_this_cycle.clear()
                
                # Process the pair signal with consistent data
                self.calcular_senal_pares()
                

class CryptoMarketMaker(Estrategia):
    def __init__(self, velas, eventos, lookback:int, capital:int,gamma:float):
        super().__init__(velas, eventos, lookback)
        self.capital = capital
        self.gamma = gamma
        self.velas = velas
        self.lookback = lookback
        self.q = 0    # Initial inventory
    
    def calibra_parametros_as(self):
        """
        Calibra los parámetros de Avellaneda-Stoikov
        Utiliza la serie de precios para calcular los parámetros
        Parámetros
        serie - Serie de precios como un DataFrame de Pandas

        """
        try:
            s_maker=self.velas.get_top_of_book('BINANCE')
            
            # Validate tuple data - check for None or invalid values
            if (s_taker is None or s_maker is None or 
                s_taker == (None, None) or s_maker == (None, None) or
                s_taker[0] is None or s_taker[1] is None or
                s_maker[0] is None or s_maker[1] is None or
                pd.isna(s_taker[1]) or pd.isna(s_maker[1])):
                print("Warning: Invalid market data for strategy calculation")
                return None, None, None, None
                
            s = (s_taker[1] + s_maker[1]) / 2
            
            # Get historic prices with proper error handling
            try:
                historic_prices = self.velas.get_historic_price(freq='1min')
                
                # Check if we got valid data - handle both DataFrame and Series
                if historic_prices is None:
                    print("Warning: No historic price data returned")
                    sigma = 0.1  # Default volatility
                elif hasattr(historic_prices, 'empty') and historic_prices.empty:
                    print("Warning: Empty historic price data")
                    sigma = 0.1  # Default volatility
                elif hasattr(historic_prices, 'isna'):
                    # Handle Series or DataFrame
                    if isinstance(historic_prices, pd.DataFrame):
                        if historic_prices.isna().all().all():  # For DataFrame
                            print("Warning: All historic price data is NaN")
                            sigma = 0.1  # Default volatility
                        else:
                            # Calculate volatility from DataFrame
                            clean_data = historic_prices.dropna()
                            if len(clean_data) > 0:
                                # Assume price column exists, otherwise use first numeric column
                                price_col = 'price_close' if 'price_close' in clean_data.columns else clean_data.select_dtypes(include=[np.number]).columns[0]
                                sigma = clean_data[price_col].std() * np.sqrt(60*24)/clean_data[price_col].iloc[-1]
                            else:
                                sigma = 0.1
                    else:  # Series
                        if historic_prices.isna().all():  # For Series
                            print("Warning: All historic price data is NaN")
                            sigma = 0.1  # Default volatility
                        else:
                            clean_data = historic_prices.dropna()
                            if len(clean_data) > 0:
                                sigma = clean_data.std() * np.sqrt(60*24)
                            else:
                                sigma = 0.1
                else:
                    sigma = 0.1  # Default volatility
                    
            except Exception as e:
                print(f"Error getting historic prices: {e}")
                sigma = 0.1  # Default volatility
                
            k=22 #Asume que la llegada de órdenes es 5 por minuto
            gamma=self.gamma #Aversion al riesgo

            return s,sigma,k,gamma     
            
        except Exception as e:
            print(f"Error in calibra_parametros_as: {e}")
            return None, None, None, None


    def calcular_senal(self):
        # Implementación de la lógica de trading para el market maker
        pass


class XEMM_BTC(Estrategia):  
          
        def __init__(self, velas, eventos, inventory:int=0,gamma:float=0.9):

            """
            Implementa el método de reversión a la media de Avellaneda (2007)
            inicializa la estrategia.
            Parámetros
            velas - El objeto de AdminDatos que gotea la info en la estrategia
            eventos- La fila de eventos ( como objeto).
            lookback - El número de periodos para calcular la volatilidad histórica
            alpha - El parámetro de suavizamient
            """
            self.velas = velas
            self.lista_nemos = self.velas.lista_nemos
            self.eventos = eventos
            self.q = inventory
            self.gamma = gamma
            self.datetime = datetime.now(timezone.utc) #Tiempo actual con timezone-aware datetime
            

        def update_inventory(self,evento):
            #Actualiza el inventario a partir de los calces reportados por el OMS
            if evento.direccion == 'buy':
                self.q += evento.cantidad
            elif evento.direccion == 'sell':
                self.q -= evento.cantidad

        def calcularPuntas(self,q): 
            #Calcula las puntas de Bid y Ask
            try:
                params = self.calibra_parametros_as()
                if params is None or any(p is None for p in params):
                    return None, None, None
                s,sigma,k,gamma = params
                r_q,pBid,pAsk=bk.cotizaciones_optimas(s,q,gamma,sigma,k)
                return r_q,pBid,pAsk
            except Exception as e:
                print(f"Error in calcularPuntas: {e}")
                return None, None, None

        def calcular_senales(self, evento):  # Ensure the signature matches the parent class
            """
            Genera un conjunto de señales en función del último precio operado
            y la distribución de probabilidad de los precios. Recalcula el conjunto 
            de probabilidades y valores y ajusta las puntas
    
            Parametros
            evento - Objeto EventoMercado. 
            """
            print(f' Evento recibido en calcular senales: {evento.ticker} Bid: {evento.bid} Ask: {evento.ask} @ {evento.timeStamp}')
            if evento.type == 'MERCADO':               
                # Valida si existe arbitraje entre los dos mercados
                try:
                    print("Updating Top Of Book Binance...")
                    (bid_binance, ask_binance) = self.velas.get_top_of_book('BINANCE')
                    # Wait until data comes back
                    while bid_binance is None or ask_binance is None:
                        time.sleep(0.1)
                    print(f"Top of Book Binance - Bid: {bid_binance}, Ask: {ask_binance}")
                    
                    print("Updating Top Of Book Bitget...")
                    (bid_bitget, ask_bitget) = self.velas.get_top_of_book('BITGET')

                    # Wait until data comes back
                    while bid_bitget is None or ask_bitget is None:
                        time.sleep(1)
                    print(f"Top of Book Bitget - Bid: {bid_bitget}, Ask: {ask_bitget}")

                    # Evalua errores en los dato
                    if ask_bitget < bid_bitget or ask_binance < bid_binance:
                        print(f'"Error en datos de mercado: Bid {bid_bitget} mayor que Ask {ask_bitget}')
                        bid_bitget = (min(bid_bitget, ask_bitget))
                        bid_binance = (min(bid_binance, ask_binance))
                        ask_bitget = (max(bid_bitget, ask_bitget))
                        ask_binance = (max(bid_binance, ask_binance))

                    if (bid_bitget - ask_binance) > ((0.0003 * ask_bitget) + (0.00075 * bid_binance) + (0.0001 * bid_binance)):  # Maker Bitget+Taker Binance+gas Fee send USDT to B
                        # Si supera el spread mínimo
                        nemo = f"{self.lista_nemos[0]}-{self.lista_nemos[1]}"
                        datetime_now = datetime.now(timezone.utc)  # Use timezone-aware datetime
                        tipo = 'TAKER-MAKER'
                        fuerza = 1.0
                        # EventoSenal(p_lim_buy, p_lim_sell, nemo, datetime, tipo_senal, fuerza=1)
                        print(f"Arbitraje detectado: Comprar en BINANCE a {ask_binance}, Vender en BITGET a {bid_bitget}")
                        evento = EventoSenal(min(ask_binance, bid_bitget), max(bid_binance, bid_bitget), nemo, datetime_now, tipo, fuerza)
                        self.eventos.add_high_priority_event(evento)  # HIGH PRIORITY for signals
                        print(f"⚡ HIGH PRIORITY SIGNAL queued: {tipo} event.")

                    elif (bid_binance - ask_bitget) > ((0.0009 * ask_bitget) + (0.006 * bid_binance) + (0.0001 * ask_bitget)):  # Maker Binance+Taker Bitget+gas fee send usdt to binance
                        nemo = f"{self.lista_nemos[0]}-{self.lista_nemos[1]}"
                        datetime_now = datetime.now(timezone.utc)  # Use timezone-aware datetime
                        tipo = 'MAKER-TAKER'
                        fuerza = 1.0
                        print(f"Arbitraje detectado: Comprar BITGET a {ask_bitget}, Vender en BINANCE a {bid_binance}")
                        evento = EventoSenal(ask_bitget - 0.1, max(bid_binance, ask_bitget), nemo, datetime_now, tipo, fuerza)
                        self.eventos.add_high_priority_event(evento)  # HIGH PRIORITY for signals
                        print(f"⚡ HIGH PRIORITY SIGNAL queued: {tipo} event.")

                    else:       # Puntas maker a ambos lados
                        print('No hay arbitraje entre los dos mercados')
                        nemo = f"{self.lista_nemos[0]}-{self.lista_nemos[1]}"
                        datetime_now = datetime.now(timezone.utc)  # Use timezone-aware datetime
                        tipo = 'XEMM'  # Cross exchange Market Making
                        fuerza = 1.0
                        # EventoSenal(p_lim_buy, p_lim_sell, nemo, datetime, tipo_senal, fuerza=1)
                        evento = EventoSenal(min(bid_bitget, bid_binance), max(ask_bitget, ask_binance), nemo, datetime_now, tipo, fuerza)  # Puntas bolsa Maker
                        self.eventos.add_high_priority_event(evento)  # HIGH PRIORITY for signals
                        print(f"⚡ HIGH PRIORITY SIGNAL queued: XEMM - Buy {evento.p_lim_buy}, sell {evento.p_lim_sell}")

                    result = self.calcularPuntas(self.q)
                    if result and all(r is not None for r in result):
                        self.r_q, self.pBid, self.pAsk = result

                except Exception as e:
                    print(f"Error in calcular_senales: {e}")


# PARES COINTEGRADOS EN VELAS DE 1m
# INFO:__main__:Cointegrated pair found: BTC-DOT (p-value: 0.0477)
# INFO:__main__:Cointegrated pair found: ETH-XRP (p-value: 0.0461)
# INFO:__main__:Cointegrated pair found: SOL-XRP (p-value: 0.0398)
# INFO:__main__:Cointegrated pair found: LTC-DOT (p-value: 0.0175)
# INFO:__main__:Cointegrated pair found: LTC-GMT (p-value: 0.0498)
# INFO:__main__:Cointegrated pair found: ADA-AVAX (p-value: 0.0409)
# INFO:__main__:Cointegrated pair found: ADA-PNUT (p-value: 0.0226)
# INFO:__main__:Cointegrated pair found: LINK-AVAX (p-value: 0.0201) !!
# INFO:__main__:Cointegrated pair found: LINK-PNUT (p-value: 0.0008)
# INFO:__main__:Cointegrated pair found: DOT-GMT (p-value: 0.0495)
# INFO:__main__:Cointegrated pair found: WLD-GMT (p-value: 0.0089)

